name = "atproto-blob-proxy"
main = "src/index.ts"
compatibility_date = "2023-07-17"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

[vars]
ATPROTO_SERVICE = "https://bsky.social"
ATPROTO_SERVICE_SUFFIX = ".bsky.social"
SERVICE_APP_URL = "https://bsky.app"
